### ISSUE TITLE
indexing very large table crashes es, no log

### ISSUE THREAD

**Issue by locojay** [jprante/elasticsearch-river-jdbc#513]
Hi
I m indexing a large psql table with about  300 million rows
Before 1.5 i used to see an info messages in the logs that x documents have been indexed every y rows. After updating to 1.5,  i don't see the progress message anymore.

I had to set `max_bulk_actions` to 100000 to avoid `rejected execution(queue capacity 50)`.
Unfortunately after a while es dies and the log is empty...

Does the river page the db ? using  limit offset ?  I suspect that the db kills the process and es dies in the process

I m currently testing` fetchsize` 100000 and `max_bulk_actions` 100000 but I now see the  `rejected execution(queue capacity 50)`  message again and the query in `pg_stat_activity` doesn't show a  limit offset.

How can I achieve paging?

thanks for helping out

**Comment by jprante** [comment]
For indexing large tables, a lot of JDBC tricks are required. With Postgresql JDBC, fetchsize > 0, no scrollable result set, no auto commit, or no holdable cursors over commit are required to setup streaming mode.

I suggest to set the parameter `"fetchsize": 10000` for Postgresql in the `jdbc` parameter block. The default is `10` which is very low for small rows. Resultset is TYPE_FORWARD_ONLY by default, and auto commit is set to false.

`max_bulk_actions` should be not that high, I recommend 10000. ES can die if that parameter is too high, but there should be some messages in the ES server log, like Out-of -memory exceptions.

To re-enable logs, just set the parameter `"metrics":"true"` in the `jdbc` parameter block (default is `false` since many users do not want metrics logging).

**Comment by jprante** [comment]
Another hint: you should try to use several SQL statements in order to partition the fetch operation of a whole table into several ones.

**Comment by locojay** [comment]
Vielen Dank.

The crash was due to OutofMemory in kern.log. 

Using multiple rivers might be the best alternative
